# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-alpine

# Set the working directory
WORKDIR /app

# Copy the jar file into the container
COPY target/silo_stream-0.0.1-SNAPSHOT.jar app.jar

# Expose port 8080 (or your app's port)
EXPOSE 8080

# Run the jar file
CMD ["java", "-jar", "app.jar"]
